name: CI/CD for EAS Builds

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development

jobs:
  get:
    runs-on: ubuntu-latest
    #needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Install dependencies
        run: npm install

      # Construcción para Android
      - name: Obtener Artefacto
        run: |
          RESPONSE=$(eas build:list --limit=1 --status=finished --json --non-interactive)
          # Extraer la URL del artefacto
          DOWNLOAD_URL=$(echo "$RESPONSE" | jq -r '.[0].artifacts.buildUrl')
          echo "La URL del artefacto obtenida es: $DOWNLOAD_URL"

          if [ ! -f "$IMAGE_PATH" ]; then
            echo "La imagen no existe en la ruta especificada: $IMAGE_PATH"
            exit 1
          fi
          echo "Ruta de la imagen: $IMAGE_PATH";

          # Enviar la imagen usando curl
          curl -X POST \
            -F "image=@$IMAGE_PATH" \
            -F "url=$DOWNLOAD_URL" \
            -F "projectName=$PROJECT_NAME" \
            "$WEB_SERVICE_URL"

        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # Asegúrate de configurar el token en GitHub Secrets
          IMAGE_PATH: ".github/workflows/logotelesecundaria763.png"
          WEB_SERVICE_URL: "https://robe.host8b.me/royerstore/subir.php"
          PROJECT_NAME: "Telesecundaria" # Cambia este valor por el nombre de tu proyecto
